Hw 2 count det
qmakar/made-cpp-2020-hw pull request #2
Opened 2020-09-29 19:29 UTC by qmakar

2020-10-01 13:00 UTC, xterrafunny requested changes

2020-10-01 13:00 UTC, xterrafunny commented on count_det/src/main.s
> +
Необходимо положить на стек значения регистров `r4-...`, значения которых изменяются во время работы функции, так как они могли хранить данные вне функции

2020-10-01 13:00 UTC, xterrafunny commented on count_det/src/main.s
> +bx lr
А здесь необходимо сделать `pop` со стека

2020-10-05 19:28 UTC, qmakar commented on count_det/src/main.s
> +
Проверьте, пожалуйста.

2020-10-08 18:10 UTC, merged